
import { supabase } from '@/integrations/supabase/client';

export interface Case {
  id: string;
  case_id: string;
  case_name: string;
  status: 'new' | 'assigned' | 'in_progress' | 'pending_review' | 'cleared' | 'str_filed' | 'closed' | 'on_hold';
  assigned_to: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
  overall_risk_level: 'Low' | 'Medium' | 'High' | 'Critical' | null;
  user_id: string;
}

export interface CaseActivityLog {
  id: string;
  case_id: string;
  user_id: string;
  activity_type: string;
  activity_description: string;
  metadata: Record<string, any>;
  created_at: string;
}

export interface CreateCaseData {
  case_name: string;
  assigned_to?: string;
  overall_risk_level?: 'Low' | 'Medium' | 'High' | 'Critical';
  created_by: string;
  user_id: string;
  status?: 'new' | 'assigned' | 'in_progress' | 'pending_review' | 'cleared' | 'str_filed' | 'closed' | 'on_hold';
}

export interface UpdateCaseData {
  case_name?: string;
  status?: 'new' | 'assigned' | 'in_progress' | 'pending_review' | 'cleared' | 'str_filed' | 'closed' | 'on_hold';
  assigned_to?: string;
  overall_risk_level?: 'Low' | 'Medium' | 'High' | 'Critical' | null;
}

export const getAllCases = async (userId: string): Promise<Case[]> => {
  const { data, error } = await supabase
    .from('cases')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching cases:', error);
    throw error;
  }

  return data as Case[];
};

export const getCaseById = async (caseId: string, userId: string): Promise<Case | null> => {
  const { data, error } = await supabase
    .from('cases')
    .select('*')
    .eq('id', caseId)
    .eq('user_id', userId)
    .single();

  if (error) {
    console.error('Error fetching case:', error);
    if (error.code === 'PGRST116') {
      return null;
    }
    throw error;
  }

  return data as Case;
};

export const createCase = async (caseData: CreateCaseData): Promise<Case> => {
  // Don't include case_id in the insert data - it will be auto-generated by the trigger
  const insertData = {
    case_name: caseData.case_name,
    assigned_to: caseData.assigned_to || null,
    overall_risk_level: caseData.overall_risk_level || null,
    created_by: caseData.created_by,
    user_id: caseData.user_id,
    status: caseData.status || 'new'
  };

  const { data, error } = await supabase
    .from('cases')
    .insert(insertData)
    .select()
    .single();

  if (error) {
    console.error('Error creating case:', error);
    throw error;
  }

  const newCase = data as Case;

  // Log the case creation activity
  await logCaseActivity({
    case_id: newCase.id,
    user_id: caseData.user_id,
    activity_type: 'case_created',
    activity_description: `Case "${caseData.case_name}" created`,
    metadata: { case_name: caseData.case_name }
  });

  return newCase;
};

export const updateCase = async (caseId: string, updateData: UpdateCaseData, userId: string): Promise<Case> => {
  const { data, error } = await supabase
    .from('cases')
    .update({ ...updateData, updated_at: new Date().toISOString() })
    .eq('id', caseId)
    .eq('user_id', userId)
    .select()
    .single();

  if (error) {
    console.error('Error updating case:', error);
    throw error;
  }

  const updatedCase = data as Case;

  // Log the case update activity
  await logCaseActivity({
    case_id: caseId,
    user_id: userId,
    activity_type: 'case_updated',
    activity_description: `Case updated`,
    metadata: updateData
  });

  return updatedCase;
};

export const deleteCase = async (caseId: string, userId: string): Promise<void> => {
  const { error } = await supabase
    .from('cases')
    .delete()
    .eq('id', caseId)
    .eq('user_id', userId);

  if (error) {
    console.error('Error deleting case:', error);
    throw error;
  }
};

export const getCaseActivityLog = async (caseId: string, userId: string): Promise<CaseActivityLog[]> => {
  const { data, error } = await supabase
    .from('case_activity_log')
    .select('*')
    .eq('case_id', caseId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching case activity log:', error);
    throw error;
  }

  // Verify user has access to this case
  const caseExists = await getCaseById(caseId, userId);
  if (!caseExists) {
    throw new Error('Access denied or case not found');
  }

  return data as CaseActivityLog[];
};

export const logCaseActivity = async (activityData: {
  case_id: string;
  user_id: string;
  activity_type: string;
  activity_description: string;
  metadata?: Record<string, any>;
}): Promise<void> => {
  const { error } = await supabase
    .from('case_activity_log')
    .insert({
      case_id: activityData.case_id,
      user_id: activityData.user_id,
      activity_type: activityData.activity_type,
      activity_description: activityData.activity_description,
      metadata: activityData.metadata || {}
    });

  if (error) {
    console.error('Error logging case activity:', error);
    throw error;
  }
};

export const linkLookupToCase = async (lookupId: string, caseId: string, userId: string): Promise<void> => {
  const { error } = await supabase
    .from('investigation_records')
    .update({ case_id_v2: caseId })
    .eq('id', lookupId)
    .eq('user_id', userId);

  if (error) {
    console.error('Error linking lookup to case:', error);
    throw error;
  }

  // Log the linking activity
  await logCaseActivity({
    case_id: caseId,
    user_id: userId,
    activity_type: 'lookup_linked',
    activity_description: `Lookup record linked to case`,
    metadata: { lookup_id: lookupId }
  });
};

export const getCaseLinkedLookups = async (caseId: string, userId: string): Promise<any[]> => {
  const { data, error } = await supabase
    .from('investigation_records')
    .select('*')
    .eq('case_id_v2', caseId)
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching case linked lookups:', error);
    throw error;
  }

  return data || [];
};

// Service class to match the expected interface
class NewCaseManagementService {
  async getAllCases(): Promise<Case[]> {
    const { data, error } = await supabase
      .from('cases')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching cases:', error);
      throw error;
    }

    return data as Case[];
  }

  async createCase(caseData: { case_name: string; overall_risk_level?: 'Low' | 'Medium' | 'High' | 'Critical' }, userId: string): Promise<{ success: boolean; case?: Case; error?: string }> {
    try {
      const insertData = {
        case_name: caseData.case_name,
        assigned_to: null,
        overall_risk_level: caseData.overall_risk_level || null,
        created_by: userId,
        user_id: userId,
        status: 'new' as const
      };

      const { data, error } = await supabase
        .from('cases')
        .insert(insertData)
        .select()
        .single();

      if (error) {
        console.error('Error creating case:', error);
        return { success: false, error: error.message };
      }

      const newCase = data as Case;

      // Log the case creation activity
      await logCaseActivity({
        case_id: newCase.id,
        user_id: userId,
        activity_type: 'case_created',
        activity_description: `Case "${caseData.case_name}" created`,
        metadata: { case_name: caseData.case_name }
      });

      return { success: true, case: newCase };
    } catch (error) {
      console.error('Error creating case:', error);
      return { success: false, error: 'Failed to create case' };
    }
  }

  async linkLookupRecordToCase(recordId: string, caseId: string, userId: string): Promise<{ success: boolean; error?: string }> {
    try {
      const { error } = await supabase
        .from('investigation_records')
        .update({ case_id_v2: caseId })
        .eq('id', recordId)
        .eq('user_id', userId);

      if (error) {
        console.error('Error linking lookup to case:', error);
        return { success: false, error: error.message };
      }

      // Log the linking activity
      await logCaseActivity({
        case_id: caseId,
        user_id: userId,
        activity_type: 'lookup_linked',
        activity_description: `Lookup record linked to case`,
        metadata: { lookup_id: recordId }
      });

      return { success: true };
    } catch (error) {
      console.error('Error linking lookup to case:', error);
      return { success: false, error: 'Failed to link record to case' };
    }
  }

  async getCaseWithLookupRecords(caseId: string): Promise<{ case: Case; lookupRecords: any[] } | null> {
    try {
      const { data: caseData, error: caseError } = await supabase
        .from('cases')
        .select('*')
        .eq('id', caseId)
        .single();

      if (caseError) {
        console.error('Error fetching case:', caseError);
        return null;
      }

      const { data: lookupData, error: lookupError } = await supabase
        .from('investigation_records')
        .select('*')
        .eq('case_id_v2', caseId)
        .order('created_at', { ascending: false });

      if (lookupError) {
        console.error('Error fetching lookup records:', lookupError);
        return null;
      }

      return {
        case: caseData as Case,
        lookupRecords: lookupData || []
      };
    } catch (error) {
      console.error('Error fetching case with lookup records:', error);
      return null;
    }
  }

  async updateCase(caseId: string, updateData: UpdateCaseData, userId: string): Promise<{ success: boolean; case?: Case; error?: string }> {
    try {
      const { data, error } = await supabase
        .from('cases')
        .update({ ...updateData, updated_at: new Date().toISOString() })
        .eq('id', caseId)
        .eq('user_id', userId)
        .select()
        .single();

      if (error) {
        console.error('Error updating case:', error);
        return { success: false, error: error.message };
      }

      const updatedCase = data as Case;

      // Log the case update activity
      await logCaseActivity({
        case_id: caseId,
        user_id: userId,
        activity_type: 'case_updated',
        activity_description: `Case updated`,
        metadata: updateData
      });

      return { success: true, case: updatedCase };
    } catch (error) {
      console.error('Error updating case:', error);
      return { success: false, error: 'Failed to update case' };
    }
  }

  async getCaseActivityLog(caseId: string): Promise<CaseActivityLog[]> {
    const { data, error } = await supabase
      .from('case_activity_log')
      .select('*')
      .eq('case_id', caseId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching case activity log:', error);
      throw error;
    }

    return data as CaseActivityLog[];
  }

  async logCaseActivity(caseId: string, userId: string, activityType: string, description: string): Promise<void> {
    await logCaseActivity({
      case_id: caseId,
      user_id: userId,
      activity_type: activityType,
      activity_description: description,
      metadata: {}
    });
  }
}

export const newCaseManagementService = new NewCaseManagementService();
