
import jsPDF from 'jspdf';
import { WalletRiskResponse } from './api';

export interface RegulatorExportData {
  wallet: WalletRiskResponse;
  recordId: string;
  caseId?: string;
  aiSummary?: string;
  analystJustification?: string;
  analystName?: string;
  timestamp: string;
  riskFactors?: any[];
  sanctionsMatches?: any[];
}

class RegulatorReportExportService {
  async exportRegulatorPDF(data: RegulatorExportData): Promise<void> {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.width;
      const pageHeight = doc.internal.pageSize.height;
      const margin = 15;
      let yPosition = 30;

      // Header with regulatory branding
      doc.setFillColor(30, 64, 175); // Blue header
      doc.rect(0, 0, pageWidth, 40, 'F');
      
      // Rìan logo area
      doc.setFillColor(59, 130, 246);
      doc.circle(margin + 8, 20, 8, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text('R', margin + 5, 24);
      
      // Main header text
      doc.setFontSize(18);
      doc.text('REGULATORY COMPLIANCE REPORT', margin + 25, 18);
      
      // Subheader
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text('AML/SAR Justification & Audit Documentation', margin + 25, 26);
      doc.text('Generated by Rìan Intelligence Platform', margin + 25, 32);

      // Document metadata in header
      doc.setFontSize(8);
      doc.text(`Generated: ${new Date(data.timestamp).toLocaleString()}`, pageWidth - margin - 60, 12);
      doc.text(`Record ID: ${data.recordId}`, pageWidth - margin - 60, 18);
      if (data.caseId) {
        doc.text(`Case ID: ${data.caseId}`, pageWidth - margin - 60, 24);
      }
      doc.text(`Analyst: ${data.analystName || 'System User'}`, pageWidth - margin - 60, 30);

      yPosition = 50;

      // Regulatory compliance statement
      doc.setFillColor(254, 242, 242);
      doc.setDrawColor(248, 113, 113);
      doc.setLineWidth(0.5);
      doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 20, 3, 3, 'FD');
      
      doc.setTextColor(185, 28, 28);
      doc.setFontSize(9);
      doc.setFont(undefined, 'bold');
      doc.text('🔒 REGULATORY COMPLIANCE DOCUMENTATION', margin + 5, yPosition + 8);
      
      doc.setFont(undefined, 'normal');
      doc.setFontSize(8);
      doc.text('This document supports AML/SAR justification and audit readiness requirements.', margin + 5, yPosition + 14);

      yPosition += 30;

      // Executive summary section
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text('EXECUTIVE SUMMARY', margin, yPosition);
      yPosition += 8;

      // Wallet details box
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(203, 213, 225);
      doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 35, 2, 2, 'FD');
      
      doc.setTextColor(71, 85, 105);
      doc.setFontSize(9);
      doc.text('Wallet Address:', margin + 5, yPosition + 8);
      doc.setFont('courier', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(8);
      const addressLines = doc.splitTextToSize(data.wallet.address, pageWidth - 2 * margin - 80);
      doc.text(addressLines, margin + 5, yPosition + 14);
      
      doc.setFont(undefined, 'normal');
      doc.setTextColor(71, 85, 105);
      doc.setFontSize(9);
      doc.text('Network:', margin + 5, yPosition + 22);
      doc.setTextColor(15, 23, 42);
      doc.setFont(undefined, 'bold');
      doc.text((data.wallet.network || 'Unknown').toUpperCase(), margin + 35, yPosition + 22);
      
      // Risk assessment in top right
      doc.setTextColor(71, 85, 105);
      doc.setFont(undefined, 'normal');
      doc.text('Risk Assessment:', pageWidth - margin - 70, yPosition + 8);
      
      let riskColor = [34, 197, 94]; // green
      if (data.wallet.risk_score >= 7) riskColor = [239, 68, 68]; // red
      else if (data.wallet.risk_score >= 4) riskColor = [245, 158, 11]; // amber
      
      doc.setFillColor(...riskColor);
      doc.roundedRect(pageWidth - margin - 70, yPosition + 12, 35, 8, 2, 2, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFont(undefined, 'bold');
      doc.setFontSize(10);
      doc.text(`${data.wallet.risk_level} (${data.wallet.risk_score}/10)`, pageWidth - margin - 67, yPosition + 18);

      yPosition += 45;

      // AI Risk Analysis section
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.text('AI RISK ANALYSIS', margin, yPosition);
      yPosition += 8;

      doc.setFillColor(240, 249, 255);
      doc.setDrawColor(147, 197, 253);
      doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 25, 2, 2, 'FD');
      
      doc.setTextColor(30, 64, 175);
      doc.setFontSize(8);
      doc.setFont(undefined, 'bold');
      doc.text(`AI Assessment Generated: ${new Date(data.timestamp).toLocaleString()}`, margin + 5, yPosition + 8);
      
      doc.setTextColor(15, 23, 42);
      doc.setFont(undefined, 'normal');
      doc.setFontSize(9);
      const aiText = data.aiSummary || `Automated risk assessment indicates ${data.wallet.risk_level.toLowerCase()} risk profile with score ${data.wallet.risk_score}/10. Analysis encompasses sanctions screening, entity attribution, and transaction pattern analysis.`;
      const aiLines = doc.splitTextToSize(aiText, pageWidth - 2 * margin - 10);
      doc.text(aiLines.slice(0, 2), margin + 5, yPosition + 16);

      yPosition += 35;

      // Compliance signals section
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.text('COMPLIANCE VERIFICATION', margin, yPosition);
      yPosition += 8;

      const signals = [
        { label: 'Sanctions Screening', status: data.wallet.risk_factors?.sanctioned ? '⚠️ FLAGGED' : '✅ CLEAR' },
        { label: 'Darknet Exposure', status: data.wallet.risk_factors?.darknet ? '🚫 DETECTED' : '✅ CLEAR' },
        { label: 'Mixer Interaction', status: data.wallet.risk_factors?.mixer_usage ? '⚠️ FLAGGED' : '✅ CLEAR' },
        { label: 'Entity Attribution', status: data.wallet.entity_attribution?.confidence ? `✅ ${Math.round(data.wallet.entity_attribution.confidence * 100)}%` : '⚠️ LOW' }
      ];

      signals.forEach((signal, index) => {
        const boxY = yPosition + (index * 12);
        
        doc.setFillColor(248, 250, 252);
        doc.setDrawColor(203, 213, 225);
        doc.rect(margin, boxY, pageWidth - 2 * margin, 10, 'FD');
        
        doc.setTextColor(71, 85, 105);
        doc.setFontSize(9);
        doc.text(signal.label + ':', margin + 5, boxY + 6);
        
        doc.setTextColor(15, 23, 42);
        doc.setFont(undefined, 'bold');
        doc.text(signal.status, pageWidth - margin - 50, boxY + 6);
        doc.setFont(undefined, 'normal');
      });

      yPosition += 55;

      // Analyst justification section
      if (data.analystJustification) {
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(11);
        doc.setFont(undefined, 'bold');
        doc.text('ANALYST PROFESSIONAL JUSTIFICATION', margin, yPosition);
        yPosition += 8;

        doc.setFillColor(254, 252, 232);
        doc.setDrawColor(217, 199, 112);
        const justificationHeight = Math.min(30, Math.max(20, data.analystJustification.length / 4));
        doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, justificationHeight, 2, 2, 'FD');
        
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(9);
        doc.setFont(undefined, 'normal');
        const justificationLines = doc.splitTextToSize(data.analystJustification, pageWidth - 2 * margin - 10);
        doc.text(justificationLines, margin + 5, yPosition + 8);

        yPosition += justificationHeight + 10;
      }

      // Footer section
      const footerY = pageHeight - 35;
      doc.setDrawColor(203, 213, 225);
      doc.setLineWidth(0.5);
      doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
      
      doc.setFillColor(248, 250, 252);
      doc.rect(0, footerY, pageWidth, 35, 'F');
      
      // Regulatory statement
      doc.setTextColor(185, 28, 28);
      doc.setFontSize(8);
      doc.setFont(undefined, 'bold');
      doc.text('REGULATORY COMPLIANCE:', margin, footerY + 8);
      doc.setTextColor(71, 85, 105);
      doc.setFont(undefined, 'normal');
      doc.text('This document has been generated in accordance with AML/KYC regulatory requirements', margin, footerY + 14);
      doc.text('and serves as official documentation for compliance audits and SAR filings.', margin, footerY + 20);
      
      // Document info
      doc.setFontSize(7);
      doc.text('© Rìan Intelligence Platform | Confidential & Proprietary', margin, footerY + 28);
      doc.text(`Page 1 of 1 | Generated: ${new Date().toLocaleDateString()}`, pageWidth - margin - 50, footerY + 28);

      // Generate filename and save
      const filename = `rian-regulator-report-${data.recordId}-${Date.now()}.pdf`;
      doc.save(filename);

      console.log('Regulatory compliance PDF generated successfully:', filename);
    } catch (error) {
      console.error('Error generating regulatory PDF:', error);
      throw new Error('Failed to generate regulatory compliance report');
    }
  }
}

export const regulatorReportExportService = new RegulatorReportExportService();
