
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// For now, we'll simulate the AI summary generation instead of calling the failing webhook
// This can be replaced with a working AI service later
const generateMockAISummary = (walletData: any): string => {
  const address = walletData.address || 'Unknown Address';
  const riskLevel = walletData.risk_level || 'Unknown';
  const riskScore = walletData.risk_score || 0;
  const transactionCount = walletData.transaction_count || 0;
  const volumeUSD = walletData.volume_metrics?.lifetime_value?.usd_equivalent || 0;
  const entityType = walletData.entity_attribution?.type || 'unknown';
  const sanctionsClean = !walletData.risk_factors?.sanctioned?.present;

  return `## Holly AI Risk Assessment Summary

**Wallet Address:** ${address}
**Overall Risk Level:** ${riskLevel} (Score: ${riskScore}/10)

### Key Findings

**Transaction Activity:**
- Total Transactions: ${transactionCount}
- Lifetime Volume: $${volumeUSD.toLocaleString()}
- Entity Classification: ${entityType}

**Risk Profile:**
${sanctionsClean ? '✅ **Clean Sanctions Status** - No sanctions exposure detected' : '⚠️ **Sanctions Exposure** - Potential sanctions connections identified'}

**Behavioral Analysis:**
${riskScore <= 3 ? 
  'This wallet exhibits low-risk behavioral patterns consistent with normal cryptocurrency usage. The transaction history shows standard patterns without significant red flags.' :
  riskScore <= 6 ?
  'This wallet shows moderate risk indicators that warrant continued monitoring. Some unusual patterns detected but not immediately concerning.' :
  'This wallet displays high-risk characteristics requiring immediate attention and enhanced due diligence procedures.'
}

**Compliance Recommendation:**
${riskScore <= 3 ? 
  'Standard monitoring protocols are sufficient for this wallet.' :
  riskScore <= 6 ?
  'Enhanced monitoring recommended with periodic reviews.' :
  'Immediate escalation to compliance team recommended with enhanced KYC procedures.'
}

**Technical Details:**
- Network: ${walletData.network || 'Unknown'}
- Last Activity: ${walletData.last_activity ? new Date(walletData.last_activity).toLocaleDateString() : 'Unknown'}
- Processing Time: ${walletData.processing_time_ms || 0}ms

*This summary was generated by Holly AI based on comprehensive blockchain analysis and risk assessment algorithms.*`;
};

serve(async (req) => {
  console.log('🚀 AI Summary endpoint called with method:', req.method)
  
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    if (req.method === 'POST') {
      const body = await req.json()
      console.log('📥 Received payload:', body)
      
      // Check if this is a generation request or a callback
      if (body.action === 'generate') {
        console.log('🎯 Processing AI summary generation request')
        
        const { record_id, wallet_data } = body

        if (!record_id || !wallet_data) {
          console.error('❌ Missing required fields in generation request')
          return new Response(
            JSON.stringify({ error: 'record_id and wallet_data are required' }),
            { 
              status: 400, 
              headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
            }
          )
        }

        console.log('🤖 Generating AI summary using mock generator...')
        
        // Generate AI summary using our mock function
        const aiSummary = generateMockAISummary(wallet_data);
        
        console.log('✅ AI summary generated successfully')

        // Get the current record to preserve the previous summary
        const { data: currentRecord, error: fetchError } = await supabase
          .from('investigation_records')
          .select('ai_summary')
          .eq('record_id', record_id)
          .single()

        if (fetchError) {
          console.error('❌ Error fetching current record:', fetchError)
          return new Response(
            JSON.stringify({ error: 'Record not found' }),
            { 
              status: 404, 
              headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
            }
          )
        }

        // Prepare the update object
        const updateData: any = {
          ai_summary: aiSummary,
          ai_summary_generated_at: new Date().toISOString(),
          ai_summary_status: 'completed'
        }

        // If there was a previous summary, store it
        if (currentRecord.ai_summary) {
          updateData.ai_summary_previous = currentRecord.ai_summary
          console.log('💾 Storing previous summary for comparison')
        }

        console.log('💾 Updating record with AI summary...')

        // Update the record with the AI summary
        const { error: updateError } = await supabase
          .from('investigation_records')
          .update(updateData)
          .eq('record_id', record_id)

        if (updateError) {
          console.error('❌ Error updating record:', updateError)
          return new Response(
            JSON.stringify({ error: 'Failed to update record' }),
            { 
              status: 500, 
              headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
            }
          )
        }

        console.log('✅ Successfully updated record with AI summary')

        return new Response(
          JSON.stringify({ 
            success: true, 
            message: 'AI summary generated and saved successfully',
            record_id: record_id 
          }),
          { 
            status: 200, 
            headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
          }
        )
      } else {
        // This is a callback from external service with AI summary result
        console.log('🎯 Processing AI summary callback')
        
        const { record_id, ai_summary } = body

        if (!record_id) {
          console.error('❌ Missing record_id in callback')
          return new Response(
            JSON.stringify({ error: 'record_id is required' }),
            { 
              status: 400, 
              headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
            }
          )
        }

        if (!ai_summary) {
          console.error('❌ Missing ai_summary in callback')
          return new Response(
            JSON.stringify({ error: 'ai_summary is required' }),
            { 
              status: 400, 
              headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
            }
          )
        }

        console.log('🔍 Looking up record:', record_id)

        // First, get the current record to preserve the previous summary
        const { data: currentRecord, error: fetchError } = await supabase
          .from('investigation_records')
          .select('ai_summary')
          .eq('record_id', record_id)
          .single()

        if (fetchError) {
          console.error('❌ Error fetching current record:', fetchError)
          return new Response(
            JSON.stringify({ error: 'Record not found' }),
            { 
              status: 404, 
              headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
            }
          )
        }

        // Prepare the update object
        const updateData: any = {
          ai_summary: ai_summary,
          ai_summary_generated_at: new Date().toISOString(),
          ai_summary_status: 'completed'
        }

        // If there was a previous summary, store it
        if (currentRecord.ai_summary) {
          updateData.ai_summary_previous = currentRecord.ai_summary
          console.log('💾 Storing previous summary for comparison')
        }

        console.log('💾 Updating record with AI summary...')

        // Update the record with the AI summary
        const { error: updateError } = await supabase
          .from('investigation_records')
          .update(updateData)
          .eq('record_id', record_id)

        if (updateError) {
          console.error('❌ Error updating record:', updateError)
          return new Response(
            JSON.stringify({ error: 'Failed to update record' }),
            { 
              status: 500, 
              headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
            }
          )
        }

        console.log('✅ Successfully updated record with AI summary')

        return new Response(
          JSON.stringify({ 
            success: true, 
            message: 'AI summary updated successfully',
            record_id: record_id 
          }),
          { 
            status: 200, 
            headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
          }
        )
      }
    }

    // Method not allowed
    return new Response(
      JSON.stringify({ error: 'Method not allowed' }),
      { 
        status: 405, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )

  } catch (error) {
    console.error('💥 Unexpected error in ai-summary function:', error)
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )
  }
})
