import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const userClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const { data: claims, error: authErr } = await userClient.auth.getClaims(
      authHeader.replace("Bearer ", ""),
    );
    if (authErr || !claims?.claims?.sub) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const body = await req.json();
    const messages: ChatMessage[] = Array.isArray(body.messages) ? body.messages : [];
    const ctx = body.context ?? {};

    if (messages.length === 0) {
      return new Response(JSON.stringify({ error: "messages required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Build a compact investigation context
    const ctxLines: string[] = [];
    if (ctx.address) ctxLines.push(`Wallet: ${ctx.address}`);
    if (ctx.network) ctxLines.push(`Network: ${ctx.network}`);
    if (typeof ctx.risk_score === "number")
      ctxLines.push(`Risk score: ${ctx.risk_score}/100`);
    if (ctx.risk_level) ctxLines.push(`Risk level: ${ctx.risk_level}`);
    if (Array.isArray(ctx.risk_factors) && ctx.risk_factors.length) {
      ctxLines.push(
        `Risk factors: ${ctx.risk_factors
          .slice(0, 8)
          .map((f: any) => `${f.factor_type ?? f.type ?? "factor"} (${f.severity ?? "?"})`)
          .join(", ")}`,
      );
    }
    if (Array.isArray(ctx.sanctions) && ctx.sanctions.length) {
      ctxLines.push(
        `Sanctions hits: ${ctx.sanctions
          .slice(0, 5)
          .map((s: any) => `${s.entity_name ?? "Unknown"} [${s.source_list ?? "?"}]`)
          .join(", ")}`,
      );
    }
    if (Array.isArray(ctx.counterparties) && ctx.counterparties.length) {
      ctxLines.push(
        `Top counterparties: ${ctx.counterparties
          .slice(0, 5)
          .map((c: any) => `${c.entity_name ?? c.address?.slice(0, 8) ?? "?"} (${c.risk_level ?? "?"})`)
          .join(", ")}`,
      );
    }

    const systemPrompt = `You are Holly, a senior blockchain compliance investigator AI assistant on the Rìan platform.
You help analysts interpret wallet risk, sanctions exposure, counterparty intelligence, and draft investigation narratives.
Be concise, factual, and use markdown (bold, lists) for clarity. When uncertain, say so.
Never invent transactions, addresses, or sanctions list entries.

When the user asks for a SAR (Suspicious Activity Report) narrative, produce a compliance-ready draft using EXACTLY these markdown sections, in order, grounded ONLY in the provided context:

**SUSPICIOUS ACTIVITY REPORT — NARRATIVE (DRAFT)**

### 1. Subject
- Wallet address, network, and any attributed entity.

### 2. Summary of Suspicious Activity
- 2–4 sentence plain-English summary of what was observed and why it is suspicious.

### 3. Risk Assessment
- Risk score and tier, with the top risk factors as a bulleted list (factor — severity — brief rationale).

### 4. Sanctions & Watchlist Exposure
- Direct hits and proximity exposure. State "No direct sanctions hits identified" if none.

### 5. Counterparty & Transaction Patterns
- Notable counterparties, mixer/exchange exposure, volume or frequency anomalies.

### 6. Regulatory Relevance
- Cite applicable frameworks (BSA/AML, FinCEN SAR, FATF Travel Rule, OFAC) where relevant.

### 7. Recommended Action
- One of: File SAR / Continue Monitoring / Escalate to MLRO / Block & Report. Justify in one sentence.

### 8. Analyst Notes
- Placeholder line: "_To be completed by reviewing analyst._"

End the narrative with: "*Draft generated by Holly — analyst review and verification required prior to filing.*"

Current investigation context:
${ctxLines.length ? ctxLines.join("\n") : "(no investigation loaded)"}`;

    const upstream = await fetch(
      "https://ai.gateway.lovable.dev/v1/chat/completions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${LOVABLE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-3-flash-preview",
          stream: true,
          messages: [
            { role: "system", content: systemPrompt },
            ...messages.map((m) => ({ role: m.role, content: m.content })),
          ],
        }),
      },
    );

    if (!upstream.ok) {
      if (upstream.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit reached. Please try again shortly." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }
      if (upstream.status === 402) {
        return new Response(
          JSON.stringify({ error: "AI credits exhausted. Add funds in Workspace Settings." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }
      const txt = await upstream.text();
      console.error("AI gateway error", upstream.status, txt);
      return new Response(JSON.stringify({ error: "AI gateway error" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(upstream.body, {
      headers: { ...corsHeaders, "Content-Type": "text/event-stream" },
    });
  } catch (e) {
    console.error("ask-holly error", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
