// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-investigations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-investigations.ts
var list_investigations_default = defineTool({
  name: "list_investigations",
  title: "List investigations",
  description: "List the signed-in analyst's recent wallet investigation records, newest first, with risk score and level.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max records to return (default 10)."),
    risk_level: z.enum(["low", "medium", "high", "critical"]).optional().describe("Filter by risk level."),
    search: z.string().trim().min(3).optional().describe("Filter by wallet address substring.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, risk_level, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("investigation_records").select(
      "id, record_id, wallet_address, network, risk_score, risk_level, investigation_status, is_case, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (risk_level) query = query.eq("risk_level", risk_level);
    if (search) query = query.ilike("wallet_address", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { records: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-investigation.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_investigation_default = defineTool2({
  name: "get_investigation",
  title: "Get investigation",
  description: "Fetch one investigation record owned by the signed-in analyst, including its AI summary and analysis data. Look it up by record_id or by wallet address.",
  inputSchema: {
    record_id: z2.string().trim().min(1).optional().describe("The record_id of the investigation."),
    wallet_address: z2.string().trim().min(1).optional().describe("Wallet address to fetch the most recent investigation for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ record_id, wallet_address }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!record_id && !wallet_address) {
      return {
        content: [{ type: "text", text: "Provide either record_id or wallet_address." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("investigation_records").select("*").order("created_at", { ascending: false }).limit(1);
    if (record_id) query = query.eq("record_id", record_id);
    else query = query.ilike("wallet_address", wallet_address);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No matching investigation found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { record: data }
    };
  }
});

// src/lib/mcp/tools/screen-address.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var screen_address_default = defineTool3({
  name: "screen_address",
  title: "Screen address against sanctions",
  description: "Screen a crypto wallet address against the synced OFAC sanctions address list and report any direct matches.",
  inputSchema: {
    address: z3.string().trim().min(4).describe("The wallet address to screen.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ address }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sanctions_addresses").select("address, entity_name, source_list, program, network, date_listed").ilike("address", address).limit(10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const hits = data ?? [];
    const text = hits.length ? `SANCTIONS MATCH for ${address}:
${JSON.stringify(hits, null, 2)}` : `No direct sanctions match found for ${address}.`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { address, sanctioned: hits.length > 0, hits }
    };
  }
});

// src/lib/mcp/tools/analyze-wallet.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var analyze_wallet_default = defineTool4({
  name: "analyze_wallet",
  title: "Analyze wallet risk",
  description: "Run a full live risk analysis on a crypto wallet address (BTC, ETH or Solana): sanctions screening, on-chain activity, wallet age, and behavioural risk factors. Returns a verdict (safe/caution/danger) and a 0-100 risk score.",
  inputSchema: {
    address: z4.string().trim().min(4).describe("The wallet address to analyze.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ address }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.functions.invoke("safe-check", {
      body: { address }
    });
    if (error) {
      return { content: [{ type: "text", text: `Analysis failed: ${error.message}` }], isError: true };
    }
    if (data?.error) {
      return { content: [{ type: "text", text: String(data.error) }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-watched-wallets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_watched_wallets_default = defineTool5({
  name: "list_watched_wallets",
  title: "List watched wallets",
  description: "List wallets the signed-in analyst is monitoring, with current and initial risk scores.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("Max wallets to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("watched_wallets").select(
      "id, wallet_address, network, status, watch_reason, alert_threshold, initial_risk_score, current_risk_score, last_checked"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { wallets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/watch-wallet.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var watch_wallet_default = defineTool6({
  name: "watch_wallet",
  title: "Watch a wallet",
  description: "Add a wallet address to the signed-in analyst's monitoring list.",
  inputSchema: {
    wallet_address: z6.string().trim().min(4).describe("Wallet address to monitor."),
    network: z6.enum(["bitcoin", "ethereum", "solana"]).describe("Blockchain network for the address."),
    watch_reason: z6.string().trim().max(500).optional().describe("Why this wallet is being monitored."),
    alert_threshold: z6.number().int().min(1).max(100).optional().describe("Risk score increase that should trigger an alert (default 10).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ wallet_address, network, watch_reason, alert_threshold }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("watched_wallets").insert({
      user_id: ctx.getUserId(),
      wallet_address,
      network,
      watch_reason: watch_reason ?? null,
      alert_threshold: alert_threshold ?? 10
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Now monitoring ${wallet_address} on ${network}.` }],
      structuredContent: { wallet: data }
    };
  }
});

// src/lib/mcp/tools/unwatch-wallet.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var unwatch_wallet_default = defineTool7({
  name: "unwatch_wallet",
  title: "Stop watching a wallet",
  description: "Remove a wallet address from the signed-in analyst's monitoring list.",
  inputSchema: {
    wallet_address: z7.string().trim().min(4).describe("Wallet address to stop monitoring.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ wallet_address }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("watched_wallets").delete().eq("user_id", ctx.getUserId()).ilike("wallet_address", wallet_address).select("wallet_address, network");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const removed = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: removed.length ? `Stopped monitoring ${wallet_address}.` : `No monitored wallet found matching ${wallet_address}.`
        }
      ],
      structuredContent: { removed: removed.length, wallets: removed }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var list_alerts_default = defineTool8({
  name: "list_alerts",
  title: "List monitoring alerts",
  description: "List recent risk alerts raised on the signed-in analyst's monitored wallets, newest first.",
  inputSchema: {
    limit: z8.number().int().min(1).max(100).optional().describe("Max alerts to return (default 20)."),
    unread_only: z8.boolean().optional().describe("Only return alerts that have not been read.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("watch_alerts").select(
      "id, alert_type, alert_message, old_value, new_value, risk_change, is_read, created_at, watched_wallets!inner(wallet_address, network, user_id)"
    ).eq("watched_wallets.user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const alerts = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: alerts.length ? JSON.stringify(alerts, null, 2) : "No alerts found."
        }
      ],
      structuredContent: { alerts }
    };
  }
});

// src/lib/mcp/tools/investigate-downstream.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.25.76";
var investigate_downstream_default = defineTool9({
  name: "investigate_downstream",
  title: "Start autonomous downstream investigation",
  description: "Launch the autonomous forensic agent on a wallet address. It recursively walks downstream fund flows (up to 3 hops), screens every hop against sanctions/scam/attribution data, classifies unknown smart contracts from on-chain bytecode, and drafts a cited investigative narrative. Returns the trace id; poll `get_investigation_trace` for results.",
  inputSchema: {
    address: z9.string().trim().min(4).describe("Root wallet address to investigate."),
    depth_limit: z9.number().int().min(1).max(3).optional().describe("Hops to walk downstream (default 3)."),
    reason: z9.string().max(300).optional().describe("Why this investigation was started.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ address, depth_limit, reason }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.functions.invoke("trace-agent", {
      body: {
        action: "enqueue",
        address,
        depth_limit: depth_limit ?? 3,
        source: "mcp",
        trigger_reason: reason ?? "Requested via MCP"
      }
    });
    if (error) return { content: [{ type: "text", text: `Failed to start: ${error.message}` }], isError: true };
    if (data?.error) return { content: [{ type: "text", text: String(data.error) }], isError: true };
    return {
      content: [{
        type: "text",
        text: `Autonomous investigation ${data.reused ? "already running" : "started"} for ${address}. Trace id: ${data.id}`
      }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-investigation-trace.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z10 } from "npm:zod@^3.25.76";
var get_investigation_trace_default = defineTool10({
  name: "get_investigation_trace",
  title: "Get autonomous investigation trace",
  description: "Read the result of an autonomous downstream investigation: status, every screened hop with its verdict, risk score, entity attribution and contract classification, and the cited investigative narrative once complete. Look up by trace id or by root wallet address.",
  inputSchema: {
    trace_id: z10.string().uuid().optional().describe("The trace id returned by investigate_downstream."),
    address: z10.string().trim().min(4).optional().describe("Root wallet address \u2014 returns the most recent trace.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trace_id, address }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!trace_id && !address) {
      return { content: [{ type: "text", text: "Provide trace_id or address." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("agent_traces").select("*").order("created_at", { ascending: false }).limit(1);
    query = trace_id ? query.eq("id", trace_id) : query.ilike("root_address", address);
    const { data: traces, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const trace = traces?.[0];
    if (!trace) {
      return { content: [{ type: "text", text: "No autonomous trace found." }], isError: true };
    }
    const { data: nodes } = await supabase.from("agent_trace_nodes").select("address, network, depth, status, verdict, risk_score, entity_name, entity_category, classification, labels, edge").eq("trace_id", trace.id).order("depth", { ascending: true });
    const payload = { trace, nodes: nodes ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nqjorzsehawucorvaqyi";
var mcp_default = defineMcp({
  name: "tryrian",
  title: "tryrian",
  version: "0.1.0",
  instructions: "Blockchain compliance tools for R\xECan. Use `analyze_wallet` for a full live risk analysis of any address, `screen_address` for a fast OFAC sanctions check, `list_investigations` / `get_investigation` to review saved investigation records and AI risk summaries, `list_watched_wallets` / `watch_wallet` / `unwatch_wallet` to manage monitoring, `investigate_downstream` to launch the autonomous multi-hop forensic agent and `get_investigation_trace` to read its risk tree and narrative, and `list_alerts` to read monitoring alerts. All tools act as the signed-in analyst.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    analyze_wallet_default,
    screen_address_default,
    list_investigations_default,
    get_investigation_default,
    list_watched_wallets_default,
    watch_wallet_default,
    unwatch_wallet_default,
    list_alerts_default,
    investigate_downstream_default,
    get_investigation_trace_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
